server:
  port: ${PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    client:
      exchange: ${RABBITMQ_EXCHANGE}
      routing: ${RABBITMQ_ROUTING}
  application:
    name: odeme
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibarnate:
        default_schema: gsths

swagger:
  info:
    title: ${SWAGGER_TITLE}
    version: ${SWAGGER_VERSION}
    description: ${SWAGGER_DSC}
    termsOfService: ${SWAGGER_TOS}
    contact:
      name: ${SWAGGER_NAME}
      email: ${SWAGGER_EMAIL}


fpos:
  servis:
    url: ${FPOS_URL}
spos:
  servis:
    url: ${SPOS_URL}
nakit:
  servis:
    url: ${NAKIT_URL}

